# Generated by Django 4.1.5 on 2023-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('price', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
    ]
