# Generated by Django 4.1.5 on 2023-01-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=15)),
            ],
        ),
    ]
